{{- if .Values.clearml.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-clearml-credentials
type: Opaque
data:
  access_key: {{ .Values.clearml.credentials.accessKey | b64enc | quote }}
  secret_key: {{ .Values.clearml.credentials.secretKey | b64enc | quote }}
{{- end }}
